name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Build
      run: go build -v main.go

    - name: Run Linter (golint)
      run: |
        go install golang.org/x/lint/golint@latest
        golint ./... | tee golint-report.txt
      continue-on-error: true

    - name: Check Code Formatting (gofmt)
      run: |
        gofmt -l .
        if [ $? -ne 0 ]; then
          echo "Code is not formatted correctly. Please run 'gofmt -w .' to format the code."
          exit 1
        fi

    - name: Test
      run: go test -v ./...
